### PR TITLE
Event rewrite

### LINKED ISSUE #149: May 2019 Ballot Comment: In the sentence "FHIR Patient resource describing the patient whose chart is currently in context.." Should it be the patient which chart was closed?
## May 2019 Ballot Comment: In the sentence "FHIR Patient resource describing the patient whose chart is currently in context.." Should it be the patient which chart was closed?

Submitted by Ricardo Quintano Neira  on behalf of @bvdh
**Chapter/section:**  Event Catalog (close-patient-chart)
**Url:** https://fhircast.hl7.org/specification/May2019Ballot/index.html
**Type:** A-S Correction

**Summary:** In the sentence "FHIR Patient resource describing the patient whose chart is currently in context.." Should it be the patient which chart was closed?

**Comment:** In the sentence "FHIR Patient resource describing the patient whose chart is currently in context..".

Should it be the patient which chart was closed?

**Existing wording:** FHIR Patient resource describing the patient whose chart is currently in context..

---
_This issue was imported by @hl7-fhircast-bot from the [consolidated FHIRcast May 2019 ballot spreadsheet](https://bit.ly/fhircast-May-2019-ballot-comments)._

### PR DESCRIPTION
**Pull request by isaacvetter**
Fixes #149, #156, #101, #102, #146, #147, #148, #161, #163, #165, #166, #156, #167, #108, #213, #211, #155, #151, #150, #154, #153, #152, #107, #210, #172, #160, #215, #214, #228, #238

1) Remove switch events, rename events
2) Move Event Catalog out of base spec
3) Define process and documentation template to define and mature events
4) Define computable syntax for (most) events
n) Various other smaller ballot fixes

### CODE REVIEW

**Comment by isaacvetter** [comment]
Hey Niklas, Fixed! Good catch. I mostly copied the [CDS Hooks maturity model](https://cds-hooks.org/specification/1.0/#hook-maturity-model). Our FHIRcast maturity model is defined as part of the core specification, here: https://github.com/HL7/fhircast-docs/blob/f421bcdda27e8221e776bd9c564114998ebfbc6b/docs/specification/STU1.md#event-maturity-model

Isaac

**Comment by wmaethner** [comment]
Few things:
1. The JSON in the event examples isn't formatted (at least when I opened it for viewing) and instead shows up as one big section of text. Can we show it properly formatted to make it easier to read.
2. The hub topics in the examples still use the url format rather than the GUID format you added in a recent PR.
3. We call out the syncerror event as being infrastructural and not defined outside the spec like the others, yet it is still in the event catalog like the other events. Is that intended?

**Comment by isaacvetter** [comment]
Hey @wmaethner!
> 1. The JSON in the event examples isn't formatted (at least when I opened it for viewing) and instead shows up as one big section of text. Can we show it properly formatted to make it easier to read.

You mean the examples section on each event page, right? I see it as formatted when running locally, like this: 
image

And specifically, it's the "```json: markdown command that does this, for example, here: https://github.com/HL7/fhircast-docs/pull/276/files#diff-5f60a799e354568d9703b19519020082R22

Any idea what might be causing you to see something different?

> 2. The hub topics in the examples still use the url format rather than the GUID format you added in a recent PR.

Ah, darn, fixed!

> 3. We call out the syncerror event as being infrastructural and not defined outside the spec like the others, yet it is still in the event catalog like the other events. Is that intended?

It was intended. I thought that it was important to document the same information. Do you think we should move it's documentation entirely into the base spec? The base spec does describe how to use it.

**Comment by wmaethner** [comment]
1. It must just be when you look at it in the "Files Changed" section. If that's how it looks when published then we are good.
2. Cool
3. Yeah that sounds good, I just wanted to confirm

**Pull request merged**
