### PR TITLE
Content sharing update

### PR DESCRIPTION
**Pull request by bvdh**
Refines section on content sharing to include both FHIR, FHIRcast and hybrid approach.
Adds -update event to event format section.

### CODE REVIEW

**Review by EricOnFHIR — COMMENTED** [review]
UpdateBundle.fsh, * entry[delete] slice

I believe we should have 0..1 for fullUrl and resource rather than 1..1 fullUrl and 0..1 resource.

Reason, if I as a Hub do not support providing endpoints and I as a Subscriber that provides the content do not support providing endpoints nor has the content been stored in a FHIR server then there is no endpoint (no fullUrl).

Is it possible to create a resourceForDelete profile that indicates only the resourceType and id SHALL be provided?

**Review by EricOnFHIR — COMMENTED** [review]
UpdateBundle.fsh, * entry[put] slice

I believe we should have 0..1 for fullUrl and resource rather than 1..1 fullUrl and 1..1 resource.

Reason, if I as a Hub do not support providing endpoints and I as a Subscriber that provides the content do not support providing endpoints nor has the content been stored in a FHIR server then there is no endpoint (no fullUrl).  As well, if I provide a fullUrl is it necessary for me to provide a resource (even if the resource has only a subset of attributes)?

**Review by EricOnFHIR — COMMENTED** [review]
ebnf/diagram/ContentSharingEventName.png replace with content in PR#472 (consistency with FHIRresource block which is in the ebnf statements)

**Review by EricOnFHIR — COMMENTED** [review]
ebnf/input/update.ebnf replace with content in PR#472 (consistency with FHIRresource naming which is in other event EBNF statements)

**Review by EricOnFHIR — COMMENTED** [review]
input/pagecontent/2-10-ContentSharing.md

I hope I am not being inconsistent with my feedback, nevertheless in should be used sections:

FHIRcast-event based content sharing should be used:
 * when starting with FHIRcast **<- I don't understand this and recommend it be removed - each approach should (my opinion) look at the application's need and not consider what experience an individual/organization has had in its past** 
 * when exchanging transient content that will only be stored when reaching a certain level of maturity.
 * when communicating resources that may or may not be stored in the end and are used to communicate e.g. selections. E.g. selecting a measurement in an image viewer, the Observation representing this measurement may only be stored when included in the report.
 * the final content may or may not be stored in a FHIR store
 * Imaging related (worklist driven) or proprietary applications. **<- not at all related to approach used, bring back into focus the ServiceRequest scenario used internally by Siemens.  This scenario meets the above criteria and event-based content sharing is used (clearly no imaging related).  Please remove this bullet.**

**FHIR based content should be used:**

 Support of content sharing by a Hub is optional.  If supporting content sharing, a FHIRcast Hub MUST fulfill additional responsibilities:
 * when you start from FHIR and add FHIRcast. **<- see the above common on reasons should support the need, not depend on the individual/organization previous experience.  I would recommend to remove**
 * when all data (versions) needs to be persisted, for example to be robust against crashes.
 * when you already use a common FHIR server, e.g. when the applications are launched using SMART on FHIR; EHR driven/ SMART apps that are extended to support context synchronzitions applications. **<- the first makes sense to me (common FHIR server); however, the last two thoughts are irrelevant and I would request they be removed.  How applications are launched is not relevant (we launch applications using SMART on FHIR and use the event mechanism given above criteria).  We also use EHR worklists to drive imaging and reporting applications and use the event mechanism.**

**Review by EricOnFHIR — CHANGES_REQUESTED** [review]
input/pagecontent/3-6-3-diagnosticreport-update.md

Why would the eventMaturity be taken back from 2-Tested to 1-Submitted?  According to the eventMaturity model DiagnosticReport-update is clearly 2-Tested.

**Review by EricOnFHIR — COMMENTED** [review]
input/pagecontent/2-10-ContentSharing.md

In the "Content exchange within...supported in three...subsections:"
2-10-1 is FHIRcast messaging

while in the "should be" section it is FHIRcast-event

I like event-based (actually "FHIRcast event-based" would be my preferred structure), regardless these two mentions of the same approach should be consistent.

**Review by EricOnFHIR — CHANGES_REQUESTED** [review]
input/pagecontent/2-3-Events.md

why remove the "For an example" link (in *-select), I would request to put this back.  Add an example link to the open/close context change events.  Move:

FHIRcast supports all events that follow this format. The most common events definitions have been provided in the [event catalog](https://build.fhir.org/ig/HL7/fhircast-docs/branches/contentSharingUpdate/3_Events.html).

to the bottom of section 2.3.2 and in the *-update ensure there is an example link.

**Review by EricOnFHIR — CHANGES_REQUESTED** [review]
input/pagecontent/2-3-Events.md

I like this summary of Content events (likely should be "Content sharing events") and would recommend updating this section with the contents of PR#472 (if any update is appropriate) after this PR is merged).

However, I recommend going with the EBNF diagrams in PR#472 as these are consistent with the FHIRresource text and EBNF snippet in this file.

**Review by EricOnFHIR — CHANGES_REQUESTED** [review]
input/pagecontent/3-6-3-diagnosticreport-update.md

Why the big removed paragraphs (starting with "The context SHALL contain one and only one Bundle")?  There is some of this information that I believe is pretty critical.  Is the proposal to move this content (or at least some of it) to 2.10.x?  I don't see that it was moved.

**Review by EricOnFHIR — CHANGES_REQUESTED** [review]
input/pagecontent/5_glossary.md

Looks like this got a little messed up?  Specifically,

- Session is no longer a defined term but is used in other definitions
- Content is defined twice
- Session event is defined twice (the one using "Subscribers" should live)
-  I guess Anchor Context and Anchor resource are the same thing?  We use Anchor Context in other parts of the specification

**Review by EricOnFHIR — CHANGES_REQUESTED** [review]
input/fsh/GetCurrentContextBundle.fsh

Recommend that the fullUrl be 0..1 as event-based content sharing approach may not support an endpoint

**Review by EricOnFHIR — CHANGES_REQUESTED** [review]
input/pagecontent/7_design-notes.md

Please remove:

**Two base use cases for content-exchange were emerged from the discussions: one with and without a FHIR server present.

 When the Subscriber is launched using SMART on FHIR, a FHIR server is available that can and should be used for content exchange. Some Radiology spcecific uses of FHIRcast do not support a FHIR server. In these situations a distributed content exchange mechanism based on FHIRcast messages is required.

As both deployments were judged to be valid, the specification supports both options. To ensure compatibility of deployments, the specification also supports hybrid solutions where Subscribers of both types can exchange content.**

In favor of something like:

**Two base use cases for content-exchange were identified during use case analysis.  One employs a transactional, event-based exchange mechanism while the second uses content sharing content persisted in a FHIR server.   It is also possible to use both method concurrently.  A detailed description of these approaches is found in the [content sharing](2-10-ContentSharing.html) section of the specification.**

As noted in a previous comment, even if SMART on FHIR launch is used and even if there is a FHIR server available somewhere in the environment, based on other considerations using the event-based content exchange mechanism is completely valid.  Also, mentioning "Radiology specific use cases" is not relevant.

**Review by EricOnFHIR — CHANGES_REQUESTED** [review]
input/pagecontent/2-10-2-ContentSharingFHIR.md

"RESTfull API" should be "RESTful API"

**Comment by isaacvetter** [comment]
Merging now following discussion and resolution of Eric's review. Overall approach and path towards identifying a single technical communication mechanism, or a clear distinction between alternate technical communications, for content sharing.

**Review by isaacvetter — APPROVED** [review]

**Pull request merged**
