### PR TITLE
EBNF-fhircast-event-name

### PR DESCRIPTION
**Pull request by isaacvetter**
Fixes: https://jira.hl7.org/browse/FHIR-37070

Where the heck is the image source?

### CODE REVIEW

**Comment by isaacvetter** [comment]
From here: https://www.bottlecaps.de/rr/ui

**Comment by isaacvetter** [comment]
New image not showing up here, though: https://build.fhir.org/ig/HL7/fhircast-docs/branches/EBNF-fhircast-event-name/fhircast-smart-scopes.png

**Comment by isaacvetter** [comment]
Hey @bvdh , this was your jira. Fix look okay?

**Comment by bvdh** [comment]
Looks good

**Pull request merged**
