### PR TITLE
Add encounter-open,close

### LINKED ISSUE #323: Support "Encounter" events
**What**
Along with Patient syncing, many applications want or need to know the encounter context as well. FHIRcast currently "supports" that within the Patient events as an extra contextual resource, but I think it should be its own explicit set of events.

FHIRcast already supports the creation of new events that follow the specified format shown below. So "Encounter-open/close" are technically allowed based on the current spec, but if we move in that direction then we should do two things:
1. Include those events in the event catalog. That isn't part of the official spec so maybe that is just getting agreement here in Github or on a call.
2. Remove the Encounter context from the Patient events. 

image

**Why**
Encounter is enough of a major concept that it deserves its own events rather than being tied into the Patient events.

Also the current method doesn't have a great way of supporting switching between encounters for the same patient. Consider the scenario that you open up Patient A and Encounter A. We would currently send a Patient-open event that includes the Encounter resource as well. The user then switches from Encounter A to Encounter B. Depending on the how the application works this could mean closing Encounter A, but the important point here is that the Patient is the same and is never closed. There isn't a good way of handling this currently. 
- Do we send a Patient-close event with Encounter A then a Patient-open with Encounter B? Since the patient never closed, this feels wrong.
- Do we just send a Patient-open with Encounter B? What happened to Encounter A? Is it closed or still open?

### PR DESCRIPTION
**Pull request by isaacvetter**
Fixes #323

### CODE REVIEW

**Comment by GinoCanessa** [comment]
I'm worried about how the events line up.  Specifically, since `encounter-close` says:
```quote
User closed patient's medical record encounter context. A previously open and in context patient chart & encounter is no longer open nor in context.
```
it becomes a lot of work to process moving between encounters on the same patient.

**Comment by isaacvetter** [comment]
> it becomes a lot of work to process moving between encounters on the same patient.

Thanks, @GinoCanessa ! I changed to:
>User closed patient's medical record encounter context. A previously open and in context patient encounter is no longer open nor in context. 

to clarify that the patient's chart was necessary to close to satisfy an `encounter-close`. Is it a lot of work to move between encounters on the same patient? I'm not sure. Note that moving between encounters on the same patient isn't a typical clinical workflow, but could be typical in an back-office / audit / review / billing workflow. The work involved is generated an open and close event for each encounter navigated to...

What do you think?

**Comment by GinoCanessa** [comment]
Thanks @isaacvetter !

I think it was me incorrectly (or maybe just too aggressively) mapping the event - I was thinking of things like opening and closing notes from prior encounters.  If that were the case, reviewing an earlier encounter would close and re-open the patient.

Unfortunately, I'm not sure how to make that clearer.  E.g., yes the user is _looking_ at a different encounter, but that's not the one in context so don't generate this message.

**Comment by isaacvetter** [comment]
The InM WG voted on this issue on 3/25/2021. 
Bas / Isaac: 9-0-0

This isn't obviously an issue that needed a formal HL7 WG vote, because this content isn't yet balloted, but it sure doesn't hurt.

**Pull request merged**
